name: deploy_to_firebase_hosting

on:
  push:
    tags:
      - release-production-*

jobs:
  deploy_to_firebase_hosting:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      
      - name: Deploy to Firebase
        uses: firebase deploy --token 1//0gxUXM9MDiIvzCgYIARAAGBASNwF-L9Irfwtx7FY7CMK-fqPLEp9Zx1B4qk9loINiolqji1-3wwR2SS-bLBhmxnxqNmit0IiXCC0 --only hosting --non-interactive
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ 1//0gxUXM9MDiIvzCgYIARAAGBASNwF-L9Irfwtx7FY7CMK-fqPLEp9Zx1B4qk9loINiolqji1-3wwR2SS-bLBhmxnxqNmit0IiXCC0 }}
